# Generated by Django 3.2.7 on 2021-10-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=128, verbose_name='язык(и)'),
        ),
    ]
