# Generated by Django 3.2.7 on 2021-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.TextField(blank=True, null=True, verbose_name='язык(и)'),
        ),
    ]
