# Generated by Django 3.2.7 on 2021-10-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.CharField(blank=True, choices=[('M', 'М'), ('Ж', 'Ж')], max_length=256, verbose_name='аватар_100'),
        ),
    ]
