# Generated by Django 3.2.7 on 2021-09-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
