# Generated by Django 3.2.7 on 2021-09-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCatergory',
            new_name='ProductCategory',
        ),
    ]
