# Generated by Django 3.2.7 on 2021-11-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
